[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["npm install", "cd backend && npm install"]

[phases.build]
cmds = ["npm run build", "cd backend && npm run build"]

[start]
cmd = "cd backend && npm start"
