services:
  # Backend + Frontend Web Service
  - type: web
    name: sengp-api
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm run build:all
    startCommand: cd backend && npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: API_VERSION
        value: v1
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: FRONTEND_URL
        sync: false
      - key: BCRYPT_ROUNDS
        value: 10

databases:
  - name: sengp-db
    databaseName: sengp_production
    user: sengp_user
    plan: free
    region: frankfurt
